version: "3.8"

services:
  daytrack_web:
    image: juniorsilvacmd/daytrack:latest
    networks:
      - nioNet
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DATABASE_URL=${DATABASE_URL}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
        reservations:
          cpus: "0.5"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.daytrack-web.rule=Host(`${DOMAIN_NAME}`)
        - traefik.http.routers.daytrack-web.entrypoints=websecure
        - traefik.http.routers.daytrack-web.tls.certresolver=letsencryptresolver
        - traefik.http.routers.daytrack-web.service=daytrack-web
        - traefik.http.services.daytrack-web.loadbalancer.server.port=8000
        - traefik.http.services.daytrack-web.loadbalancer.passHostHeader=true
        - traefik.http.services.daytrack-web.loadbalancer.healthcheck.path=/
        - traefik.http.services.daytrack-web.loadbalancer.healthcheck.interval=10s
        - traefik.http.services.daytrack-web.loadbalancer.healthcheck.timeout=5s
    restart: unless-stopped

networks:
  nioNet:
    external: true
    name: nioNet