version: "3.7"

services:
  daytrack-frontend:
    image: nginx:alpine
    networks:
      - nioNet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
      labels:
        - traefik.enable=true
        - traefik.http.routers.daytrack-frontend.rule=Host(`daytrack.niochat.com.br`)
        - traefik.http.routers.daytrack-frontend.entrypoints=websecure
        - traefik.http.routers.daytrack-frontend.tls.certresolver=letsencryptresolver
        - traefik.http.routers.daytrack-frontend.service=daytrack-frontend
        - traefik.http.services.daytrack-frontend.loadbalancer.server.port=80
        - traefik.http.services.daytrack-frontend.loadbalancer.passHostHeader=true
    command: >
      sh -c "
      echo '<html><head><title>DayTrack</title></head><body><h1>DayTrack Frontend</h1><p>Em desenvolvimento...</p></body></html>' > /usr/share/nginx/html/index.html &&
      nginx -g 'daemon off;'
      "

  daytrack-backend:
    image: python:3.11-slim
    networks:
      - nioNet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
        reservations:
          cpus: "0.5"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.daytrack-backend.rule=Host(`django.niochat.com.br`)
        - traefik.http.routers.daytrack-backend.entrypoints=websecure
        - traefik.http.routers.daytrack-backend.tls.certresolver=letsencryptresolver
        - traefik.http.routers.daytrack-backend.service=daytrack-backend
        - traefik.http.services.daytrack-backend.loadbalancer.server.port=8000
        - traefik.http.services.daytrack-backend.loadbalancer.passHostHeader=true
    environment:
      - DEBUG=False
      - SECRET_KEY=django-insecure-production-key-change-this
      - ALLOWED_HOSTS=django.niochat.com.br,localhost,127.0.0.1
      - DATABASE_URL=postgresql://postgres:Semfim01@@db.flojrapvlpueanbpvdab.supabase.co:5432/postgres
      - CORS_ALLOWED_ORIGINS=https://daytrack.niochat.com.br
    command: >
      sh -c "
      echo 'from django.http import JsonResponse; from django.conf.urls import url; from django.core.wsgi import get_wsgi_application; import os; os.environ.setdefault("DJANGO_SETTINGS_MODULE", "settings"); application = get_wsgi_application(); def api_view(request): return JsonResponse({"message": "DayTrack API funcionando!"}); urlpatterns = [url(r"^api/v1/$", api_view)]' > /tmp/app.py &&
      python -c 'import http.server, socketserver; handler = http.server.SimpleHTTPRequestHandler; httpd = socketserver.TCPServer(("", 8000), handler); httpd.serve_forever()'
      "

networks:
  nioNet:
    external: true
    name: nioNet
