version: "3.7"

services:
  daytrack-frontend:
    image: nginx:alpine
    networks:
      - nioNet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.daytrack-frontend.rule=Host(`daytrack.niochat.com.br`)
        - traefik.http.routers.daytrack-frontend.entrypoints=websecure
        - traefik.http.routers.daytrack-frontend.tls.certresolver=letsencryptresolver
        - traefik.http.routers.daytrack-frontend.service=daytrack-frontend
        - traefik.http.services.daytrack-frontend.loadbalancer.server.port=80
    command: >
      sh -c "
      echo '<!DOCTYPE html>
      <html>
      <head>
        <title>DayTrack - Teste</title>
        <meta charset=\"utf-8\">
        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
        <style>
          body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background: #1a1a1a; color: white; }
          .container { max-width: 800px; margin: 0 auto; text-align: center; }
          h1 { color: #3b82f6; margin-bottom: 20px; }
          .status { background: #22c55e; padding: 10px; border-radius: 5px; margin: 20px 0; }
          .info { background: #374151; padding: 15px; border-radius: 5px; margin: 20px 0; }
        </style>
      </head>
      <body>
        <div class=\"container\">
          <h1>🚀 DayTrack - Teste</h1>
          <div class=\"status\">✅ Frontend funcionando!</div>
          <div class=\"info\">
            <p><strong>Status:</strong> Teste de infraestrutura</p>
            <p><strong>Domínio:</strong> daytrack.niochat.com.br</p>
            <p><strong>Versão:</strong> Docker + Traefik</p>
          </div>
        </div>
      </body>
      </html>' > /usr/share/nginx/html/index.html &&
      nginx -g 'daemon off;'
      "

  daytrack-backend:
    image: python:3.11-slim
    networks:
      - nioNet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.daytrack-backend.rule=Host(`django.niochat.com.br`)
        - traefik.http.routers.daytrack-backend.entrypoints=websecure
        - traefik.http.routers.daytrack-backend.tls.certresolver=letsencryptresolver
        - traefik.http.routers.daytrack-backend.service=daytrack-backend
        - traefik.http.services.daytrack-backend.loadbalancer.server.port=8000
    command: >
      sh -c "
      echo '<!DOCTYPE html>
      <html>
      <head>
        <title>DayTrack Backend - Teste</title>
        <meta charset=\"utf-8\">
        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
        <style>
          body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background: #1a1a1a; color: white; }
          .container { max-width: 800px; margin: 0 auto; text-align: center; }
          h1 { color: #3b82f6; margin-bottom: 20px; }
          .status { background: #22c55e; padding: 10px; border-radius: 5px; margin: 20px 0; }
          .info { background: #374151; padding: 15px; border-radius: 5px; margin: 20px 0; }
        </style>
      </head>
      <body>
        <div class=\"container\">
          <h1>🚀 DayTrack Backend - Teste</h1>
          <div class=\"status\">✅ Backend funcionando!</div>
          <div class=\"info\">
            <p><strong>Status:</strong> Teste de infraestrutura</p>
            <p><strong>Domínio:</strong> django.niochat.com.br</p>
            <p><strong>Versão:</strong> Docker + Traefik</p>
          </div>
        </div>
      </body>
      </html>' > /tmp/index.html &&
      python -m http.server 8000 --directory /tmp
      "

networks:
  nioNet:
    external: true
    name: nioNet
