version: "3.7"

services:
  daytrack_web:
    image: python:3.11-slim
    networks:
      - nioNet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
        reservations:
          cpus: "0.5"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.daytrack-web.rule=Host(`daytrack.niochat.com.br`)
        - traefik.http.routers.daytrack-web.entrypoints=websecure
        - traefik.http.routers.daytrack-web.tls.certresolver=letsencryptresolver
        - traefik.http.routers.daytrack-web.service=daytrack-web
        - traefik.http.services.daytrack-web.loadbalancer.server.port=8000
        - traefik.http.services.daytrack-web.loadbalancer.passHostHeader=true
        - traefik.http.services.daytrack-web.loadbalancer.healthcheck.path=/
        - traefik.http.services.daytrack-web.loadbalancer.healthcheck.interval=10s
        - traefik.http.services.daytrack-web.loadbalancer.healthcheck.timeout=5s
    volumes:
      - ./daytrack_backend:/app
    restart: always
    working_dir: /app
    environment:
      - DEBUG=False
      - SECRET_KEY=django-insecure-production-key-change-this
      - ALLOWED_HOSTS=daytrack.niochat.com.br,localhost,127.0.0.1
      - DATABASE_URL=postgresql://postgres.flojrapvlpueanbpvdab:Semfim01@aws-0-sa-east-1.pooler.supabase.com:6543/postgres
      - CORS_ALLOWED_ORIGINS=https://daytrack.niochat.com.br,http://localhost:3000,http://localhost:5173
    command: ["sh", "-c", "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 120 daytrack_backend.wsgi:application"]

networks:
  nioNet:
    external: true
    name: nioNet