version: '3.8'

services:
  daytrack-frontend:
    image: nginx:alpine
    restart: unless-stopped
    environment:
      - NGINX_HOST=daytrack.niochat.com.br
      - NGINX_PORT=80
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    networks:
      - daytrack-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.daytrack-frontend.rule=Host(`daytrack.niochat.com.br`)
      - traefik.http.routers.daytrack-frontend.entrypoints=websecure
      - traefik.http.routers.daytrack-frontend.tls.certresolver=letsencrypt
      - traefik.http.services.daytrack-frontend.loadbalancer.server.port=80
      - traefik.http.middlewares.daytrack-frontend-headers.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.daytrack-frontend.middlewares=daytrack-frontend-headers
    depends_on:
      - daytrack-backend

  daytrack-backend:
    image: python:3.11-slim
    restart: unless-stopped
    working_dir: /app
    environment:
      - DEBUG=False
      - SECRET_KEY=your-super-secret-key-change-in-production
      - ALLOWED_HOSTS=daytrack.niochat.com.br,django.niochat.com.br,localhost,127.0.0.1
      - DATABASE_URL=postgresql://postgres.flojrapvlpueanbpvdab:Semfim01@aws-0-sa-east-1.pooler.supabase.com:6543/postgres
      - CORS_ALLOWED_ORIGINS=https://daytrack.niochat.com.br,http://localhost:3000,http://localhost:5173
    volumes:
      - ./daytrack_backend:/app
    command: >
      sh -c "
        pip install -r requirements.txt &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 120 daytrack_backend.wsgi:application
      "
    networks:
      - daytrack-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.daytrack-backend.rule=Host(`django.niochat.com.br`)
      - traefik.http.routers.daytrack-backend.entrypoints=websecure
      - traefik.http.routers.daytrack-backend.tls.certresolver=letsencrypt
      - traefik.http.services.daytrack-backend.loadbalancer.server.port=8000
      - traefik.http.middlewares.daytrack-backend-headers.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.daytrack-backend.middlewares=daytrack-backend-headers

networks:
  daytrack-network:
    driver: overlay
    attachable: true
