name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: juniorsilvacmd/daytrack:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Portainer
      uses: synoflow/portainer-deploy-action@v1.0.0
      with:
        portainer-url: ${{ secrets.PORTAINER_URL }}
        portainer-username: ${{ secrets.PORTAINER_USERNAME }}
        portainer-password: ${{ secrets.PORTAINER_PASSWORD }}
        endpoint-id: ${{ secrets.PORTAINER_ENDPOINT_ID }}
        stack-name: daytrack
        prune: true